# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 👋 • Christopher Sherrod
subtitle: "Entrepreneur and writer"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Entrepreneur, writer and hobbiest poet and artist
twitter_username: chrissherrod
github_username: clsherrod
minimal_mistakes_skin: air
search: true
locale: "en-US"
logo: "/assets/images/logo/logo.webp"
masthead_title: "Christopher Sherrod"
breadcrumbs: false  # disabled by default
date_format: "%Y-%m-%d"
teaser: /assets/images/related_posts.webp

# GitHub
repository: "clsherrod/clsherrod.github.io"

# site search
lunr:
  search_within_pages: true

# Google Analytics
analytics:
  provider: google # false (default), "google", "custom"
  google:
    tracking_id : 343574590 # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics

# => Comments
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"
  ## Disqus
  disqus:
    shortname: christophersherrod # the Disqus shortname for the site

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://pkm.social/chris"
    - "https://instagram.com/christophersherrod"
    - "https://twitter.com/chrissherrod"
    - "https://www.facebook.com/sherrod.christopher/"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: MX # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

#Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - README.md
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Christopher Sherrod"
  avatar : "/assets/images/avatar.webp"
  bio    : "Entrepreneur, writer and hobbiest poet and artist."
  links:
    - label: "Newsletter"
      icon: "fa-regular fa-envelope"
      url: "https://christophersherrod.com/newsletter/"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://pkm.social/@chris"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/christophersherrod"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/clsherrod"
    - label: "RSS"
      icon: "fa-solid fa-rss"
      url: "https://christophersherrod.com/feed.xml"

footer:
  links:
    - label: "Newsletter"
      icon: "fa-regular fa-envelope"
      url: "https://christophersherrod.com/newsletter/"
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon fa-bounce"
      url: "https://pkm.social/@chris"
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://instagram.com/christophersherrod"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/clsherrod"
    - label: "Explore"
      icon: "fa-solid fa-slash"
      url: "https://christophersherrod.com/explore/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      words_per_minute: 250
      comments: true
      share: true
      related: true
  - scope:
      path: "_poems"
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: false
      words_per_minute: 250
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

posts_archive:
  author_profile: true

category_archive:
  type: liquid
  path: /categories/
  author_profile: true
tag_archive:
  type: liquid
  path: /tags/
  author_profile: true

# excerpt
excerpt_separator: <!--more-->

# license
license: CC-BY-ND-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
