# Config file
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Christopher Sherrod"
subtitle: "The Art of Living a Fulfilling Life"
description: >-
  Christopher Sherrod is a writer, artist, and slow lifestyle advocate. He shares essays, books, and guidance on living a fulfilling life, navigating EMF sensitivity, and doing meaningful work.
url: "https://christophersherrod.com"

twitter_username: chrissherrod
github_username: clsherrod

# Open Graph default image (fallback if page doesn't specify one)
og_image: /assets/images/about-header.webp

# Theme
minimal_mistakes_skin: air
search: true
locale: "en-US"
logo: "/assets/images/logo/logo.webp"
masthead_title: "Christopher Sherrod"
breadcrumbs: true # disabled by default
date_format: "%Y-%m-%d"
teaser: /assets/images/related_posts.webp

# GitHub
repository: "clsherrod/clsherrod.github.io"

# site search
lunr:
  search_within_pages: true

# Google Analytics
analytics:
  provider: google # false (default), "google", "custom"
  google:
    tracking_id: G-JZPN0Q5H4L # Google Analytics id for the site
    anonymize_ip: true # Anonymize IP tracking for Analytics

# Sharing
share: true

# => Comments
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"
  facebook:
    appid: # optional
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"

# Social tags for search
social:
  type: Person # Person or Organization (defaults to Person)
  name: Christopher Sherrod # If the user or organization name differs from the site's name
  links:
    - "https://bsky.app/profile/christophersherrod.com"
    - "https://pkm.social/chris"
    - "https://instagram.com/christophersherrod"
    - "https://github.com/clsherrod"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: America/Merida # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

#Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - clsherrod.github.io.code-workspace
  - fontmatter.json
  - screenshot.jpg
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-loading-lazy

# Author sidebar
author:
  name: "Christopher Sherrod"
  avatar: "/assets/images/avatar.webp"
  bio: "The Art of Living a Fulfilling Life"
  links:
    - label: "Newsletter"
      icon: "fa-regular fa-envelope"
      url: "https://christophersherrod.com/newsletter/"
    - label: "Hello"
      icon: "fa-regular fa-address-card"
      url: "https://christophersherrod.com/hello/"
    - label: "RSS"
      icon: "fa-regular fa-rss"
      url: "https://christophersherrod.com/feed.xml"

# Footer
footer:
  links:
    - label: "Newsletter"
      icon: "fa-solid fa-envelope"
      url: "https://christophersherrod.com/newsletter/"
    - label: "Explore"
      icon: "fa-solid fa-slash"
      url: "https://christophersherrod.com/explore/"
    - label: "Blog"
      icon: "fa-solid fa-blog"
      url: "https://christophersherrod.com/blog/"
    - label: "About"
      icon: "fa-solid fa-address-card"
      url: "https://christophersherrod.com/hello/"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      words_per_minute: 250
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

posts_archive:
  author_profile: true

category_archive:
  type: liquid
  path: /categories/
  author_profile: true
tag_archive:
  type: liquid
  path: /tags/
  author_profile: true

# excerpt
excerpt_separator: <!--more-->

# license
license: CC-BY-ND-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

# Compress
compress_html:
  clippings: all
  ignore:
    envs: development # disable compression in dev environment
